// İBB TRAFİK VERİSİ TABLOSU
Table LSTM_DESTEKLİ_İBB_BEŞİKTAŞ_VERİSİ {
 id integer [primary key, increment]
  ym varchar [note: 'Yıl ve ayın birleşik hali (Örn: 202301)']
  datetime timestamp [note: 'Tam tarih ve saat bilgisi']
  date date [note: 'Sadece gün tarihi (Yıl-Ay-Gün)']
  hour integer [note: 'Günün saati (0-23 arası)']
  weekday integer [note: 'Haftanın hangi günü olduğu (0: Pazartesi, 6: Pazar)']
  is_weekend boolean [note: 'Hafta sonu mu? (1: Evet, 0: Hayır)']
  lat float [note: 'Ölçüm noktasının enlem koordinatı']
  lon float [note: 'Ölçüm noktasının boylam koordinatı']
  location varchar [note: 'Ölçüm yapılan bölgenin adı (Örn: Beşiktaş)']
  speed float [note: 'O saat dilimindeki ortalama araç hızı (km/s)']
  density float [note: 'O saat dilimindeki trafik yoğunluğu (araç sayısı)']
  target float [note: 'Yapay zekanın (LSTM) tahmin etmeye çalışacağı asıl hedef değer']
  lag_1h float [note: 'Geçmişe dönük: 1 saat önceki trafik yoğunluk verisi']
  lag_24h float [note: 'Geçmişe dönük: Tam 1 gün (24 saat) önceki trafik yoğunluk verisi']
  lag_7d float [note: 'Geçmişe dönük: Tam 1 hafta (7 gün) önceki trafik yoğunluk verisi']
  ma_3h float [note: 'Geçmişe dönük: Son 3 saatin trafik yoğunluğu hareketli ortalaması']
  hour_sin float [note: 'LSTM in saatin döngüsel olduğunu okuyabilmesi için standart saat verisinden sinüs dönüşümüne uğramış veri']
  hour_cos float [note: 'LSTM in saatin döngüsel olduğunu okuyabilmesi için standart saat verisinden kosinüs dönüşümüne uğramış veri']
  day_sin float [note: 'LSTM in günlerin döngüsel olduğunu okuyabilmesi için standart gün verisinden sinüs dönüşümüne uğramış veri']
  day_cos float [note: 'LSTM in günlerin döngüsel olduğunu okuyabilmesi için standart gün verisinden kosinüs dönüşümüne uğramış veri']
}

